services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src:/server/src/

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db

  client:
    build: ./client
    ports:
      - 8080:5173
    # command: npm run dev --host
    volumes:
      - ./client/src:/client/src/
